### ISSUE TITLE
Write-up of extension to project proposal (Wiki)

### ISSUE THREAD

**Issue by hlac** [jeegar298/COMP313_Project2#1]

**Comment by simran1114** [comment]
Vaibhavi and Jhil, please make a document with introduction and other technical information about the current project and also write some stuff about the previous semester's project

**Comment by hlac** [comment]
Use the @ handle to communicate with your team members.

**Comment by hlac** [comment]
Besides migrating to the cloud, what are other new features that you plan to add?  List the features in the wiki, or better yet, do a low-fidelity prototype, write user stories, and disaggregate tasks.
