### ISSUE TITLE
Cloud service, nosql, and test setup

### ISSUE THREAD

**Issue by hlac** [jeegar298/COMP313_Project2#2]
Setup, configure, verify authentication, simple echo (includes database).

**Comment by ItsMeJeegar** [comment]
Using ehost.com for hosting the website
Domain Name: jeegarthecoder.com
Cloud service setup complete

**Comment by ItsMeJeegar** [comment]
Using Google's Firebase platform for nosql database
Google ID: foodCentennial@gmail.com
