### ISSUE TITLE
Designing Restaurants page

### ISSUE THREAD

**Issue by ItsMeJeegar** [jeegar298/COMP313_Project2#8]
Shows the food services available at the college campus.

**Comment by harleen311** [comment]
![capture](https://cloud.githubusercontent.com/assets/20406964/23107691/736ec9a0-f6cf-11e6-85ab-bd6bb5fb9efc.PNG)

**Comment by harleen311** [comment]
Hello guys.  I have made this restaurant page so far. Do you want me to insert any more restaurants or make any other changes?

**Comment by harleen311** [comment]
These are Tims, SuShi,, Second cup, Subway, Pizza Pizza, Marley Coffee

**Comment by vaibhu51** [comment]
yes @harleen311 it looks fine and rest we ll find if any other restaurant is left in student centre
